package dmp


class Log(
           val sessionid: String,
           val advertisersid: Int,
           val adorderid: Int,
           val adcreativeid: Int,
           val adplatformproviderid: Int,
           val sdkversion: String,
           val adplatformkey: String,
           val putinmodeltype: Int,
           val requestmode: Int,
           val adprice: Double,
           val adppprice: Double,
           val requestdate: String,
           val ip: String,
           val appid: String,
           val appname: String,
           val uuid: String,
           val device: String,
           val client: Int,
           val osversion: String,
           val density: String,
           val pw: Int,
           val ph: Int,
           val long: String,
           val lat: String,
           val provincename: String,
           val cityname: String,
           val ispid: Int,
           val ispname: String,
           val networkmannerid: Int,
            val iseffective: Int,
            val isbilling: Int,
            val adspacetype: Int,
            val adspacetypename: String,
            val devicetype: Int,
            val processnode: Int,
            val apptype: Int,
            val district: String,
            val paymode: Int,
            val isbid: Int,
            val bidprice: Double,
            val winprice: Double,
            val iswin: Int,
            val cur: String,
            val rate: Double,
            val cnywinprice: Double,
            val imei: String,
            val mac: String,
            val idfa: String,
            val openudid: String,
            val androidid: String,
            val rtbprovince: String,
            val rtbcity: String,
            val rtbdistrict: String,
            val rtbstreet: String,
            val storeurl: String,
            val realip: String,
            val isqualityapp: Int,
            val bidfloor: Double,
            val aw: Int,
            val ah: Int,
            val imeimd5: String,
            val macmd5: String,
            val idfamd5: String,
            val openudidmd5: String,
            val androididmd5: String,
            val imeisha1: String,
            val macsha1: String,
            val idfasha1: String,
            val openudidsha1: String,
            val androididsha1: String,
            val uuidunknow: String,
            val userid: String,
            val iptype: Int,
            val initbidprice: Double,
            val adpayment: Double,
            val agentrate: Double,
            val lomarkrate: Double,
            val adxrate: Double,
            val title: String,
            val keywords: String,
            val tagid: String,
            val callbackdate: String,
            val channelid: String,
            val mediatype: Int



         ) extends Product with Serializable {
  //角标和成员属性的关系
  override def productElement(n: Int): Any = n match{
    case 0 => sessionid
     // ................
  }

  override def productArity: Int = ???

  override def canEqual(that: Any): Boolean = ???
}
